spring:
  application:
    name: dorakdorak

  config:
    import: application-secret.yml

  profiles:
    active: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080



mybatis:
  mapper-locations: classpath:mapper/**/*.xml