package dorakdorak.domain.order.enums;

public enum OrderStatus {
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    GONGGOO_OPEN,
    GONGGOO_CONFIRMED,
    DELIVERY_IN_PROGRESS,
    DELIVERY_COMPLETED
}
